<?php
defined( 'ABSPATH' ) || exit;
class CFP_Database {
	public static function table( string $name ): string { global $wpdb; return $wpdb->prefix . 'cfp_' . sanitize_key( $name ); }
	public static function install(): void { global $wpdb; require_once ABSPATH . 'wp-admin/includes/upgrade.php'; $charset = $wpdb->get_charset_collate();
		$schemas = array(
			"CREATE TABLE " . self::table('funnels') . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,name VARCHAR(190) NOT NULL,type VARCHAR(60) NOT NULL DEFAULT 'sales',status VARCHAR(30) NOT NULL DEFAULT 'active',settings LONGTEXT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),KEY status(status),KEY created_at(created_at)) $charset;",
			"CREATE TABLE " . self::table('steps') . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,funnel_id BIGINT UNSIGNED NOT NULL,page_id BIGINT UNSIGNED NOT NULL,step_type VARCHAR(60) NOT NULL,title VARCHAR(190) NOT NULL,position INT NOT NULL DEFAULT 0,settings LONGTEXT NULL,status VARCHAR(30) NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL,PRIMARY KEY(id),KEY funnel_id(funnel_id),KEY step_type(step_type),KEY status(status),KEY created_at(created_at)) $charset;",
		);
		foreach ( array('events','analytics') as $t ) { $schemas[] = "CREATE TABLE " . self::table($t) . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,funnel_id BIGINT UNSIGNED NULL,step_id BIGINT UNSIGNED NULL,order_id BIGINT UNSIGNED NULL,customer_email VARCHAR(190) NULL,event_type VARCHAR(80) NOT NULL,value DECIMAL(18,4) NOT NULL DEFAULT 0,meta LONGTEXT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),KEY funnel_id(funnel_id),KEY step_id(step_id),KEY order_id(order_id),KEY customer_email(customer_email),KEY event_type(event_type),KEY created_at(created_at)) $charset;"; }
		foreach ( array('automations','emails','files','webhooks') as $t ) { $schemas[] = "CREATE TABLE " . self::table($t) . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,name VARCHAR(190) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'active',config LONGTEXT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),KEY status(status),KEY created_at(created_at)) $charset;"; }
		foreach ( array('automation_logs','email_logs','downloads','webhook_logs','abandoned_checkouts') as $t ) { $schemas[] = "CREATE TABLE " . self::table($t) . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,funnel_id BIGINT UNSIGNED NULL,step_id BIGINT UNSIGNED NULL,order_id BIGINT UNSIGNED NULL,customer_email VARCHAR(190) NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending',event_type VARCHAR(80) NULL,meta LONGTEXT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),KEY funnel_id(funnel_id),KEY step_id(step_id),KEY order_id(order_id),KEY customer_email(customer_email),KEY event_type(event_type),KEY status(status),KEY created_at(created_at)) $charset;"; }
		$schemas[] = "CREATE TABLE " . self::table('settings') . " (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,setting_key VARCHAR(190) NOT NULL,setting_value LONGTEXT NULL,autoload TINYINT(1) NOT NULL DEFAULT 0,PRIMARY KEY(id),UNIQUE KEY setting_key(setting_key)) $charset;";
		foreach ( $schemas as $schema ) { dbDelta( $schema ); } update_option( 'cfp_db_version', CFP_VERSION ); }
}
