const STORAGE_DEFAULT = { accounts: [], recentAccountIds: [], settings: { openInBackground: true } };
const ADS_URL = 'https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=';
const $ = (id) => document.getElementById(id);
let state = structuredClone(STORAGE_DEFAULT);
let query = '';
let lastScan = null;

async function getStorageData(){try{const data={...STORAGE_DEFAULT,...await chrome.storage.sync.get(STORAGE_DEFAULT)};data.settings={...STORAGE_DEFAULT.settings,...(data.settings||{})};data.recentAccountIds=[...new Set(data.recentAccountIds||[])].slice(0,5);return data}catch(e){showMessage('Could not read storage.');return structuredClone(STORAGE_DEFAULT)}}
async function saveStorageData(data){try{await chrome.storage.sync.set(data);return true}catch(e){showMessage('Could not save changes.');return false}}
function normalizeAccountId(v){return String(v||'').trim().replace(/^act_/i,'').replace(/\D/g,'')}
function validateAccount(a, existing, editingId){const errors=[]; if(!a.name.trim())errors.push('Account name cannot be empty.'); if(!normalizeAccountId(a.accountId))errors.push('Account ID cannot be empty.'); const clean=normalizeAccountId(a.accountId); if(clean&&existing.some(x=>x.accountId===clean&&x.id!==editingId))errors.push('This account ID already exists.'); return errors}
function showMessage(t){const el=$('message');el.textContent=t;el.hidden=false;setTimeout(()=>el.hidden=true,4500)}
function uuid(){return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`}
async function openAdsAccount(account){const accountObj=typeof account==='string'?state.accounts.find(a=>a.accountId===account)||{accountId:account,name:'Ad account'}:account;const active=!state.settings?.openInBackground;await chrome.tabs.create({url:ADS_URL+accountObj.accountId,active});await updateRecentAccounts(accountObj.accountId);showMessage(`Opened ${accountObj.name || 'account'} in new tab`)}
async function updateRecentAccounts(accountId){state.recentAccountIds=[accountId,...(state.recentAccountIds||[]).filter(id=>id!==accountId)].slice(0,5);await saveStorageData(state);renderAccounts()}
async function toggleFavorite(id){const a=state.accounts.find(x=>x.id===id); if(!a)return; a.isFavorite=!a.isFavorite; a.updatedAt=new Date().toISOString(); await saveStorageData(state); renderAccounts()}
async function deleteAccount(id){const a=state.accounts.find(x=>x.id===id); if(!a||!confirm(`Delete ${a.name}?`))return; state.accounts=state.accounts.filter(x=>x.id!==id); state.recentAccountIds=(state.recentAccountIds||[]).filter(x=>x!==a.accountId).slice(0,5); await saveStorageData(state); renderAccounts()}
function filteredAccounts(){const q=query.toLowerCase(); return state.accounts.filter(a=>[a.name,a.accountId,a.businessName,a.status].some(v=>String(v||'').toLowerCase().includes(q))).sort((a,b)=>(b.isFavorite-a.isFavorite)||a.name.localeCompare(b.name))}
function makeCard(a){const card=document.createElement('article');card.className='card';card.tabIndex=0;card.addEventListener('click',()=>openAdsAccount(a));card.addEventListener('keydown',e=>{if(e.key==='Enter')openAdsAccount(a)});const top=document.createElement('div');top.className='card-top';const info=document.createElement('div');const name=document.createElement('div');name.className='name';name.textContent=a.name;const meta=document.createElement('div');meta.className='meta';meta.textContent=`${a.accountId}${a.businessName?' • '+a.businessName:''}`;info.append(name,meta);if(a.status){const badge=document.createElement('span');badge.className='badge';badge.textContent=a.status;info.append(badge)}const star=document.createElement('button');star.className='tiny';star.textContent=a.isFavorite?'★':'☆';star.title='Toggle favorite';star.addEventListener('click',e=>{e.stopPropagation();toggleFavorite(a.id)});top.append(info,star);const actions=document.createElement('div');actions.className='card-actions';[['Open','open',()=>openAdsAccount(a)],['Edit','secondary',()=>showDialog(a)],['Delete','danger',()=>deleteAccount(a.id)]].forEach(([t,c,fn])=>{const b=document.createElement('button');b.className=`tiny ${c}`;b.textContent=t;b.addEventListener('click',e=>{e.stopPropagation();fn()});actions.append(b)});card.append(top,actions);return card}
function renderList(el, accounts, emptyText){el.replaceChildren(); if(!accounts.length){const p=document.createElement('p');p.className='meta';p.textContent=emptyText;el.append(p);return} accounts.forEach(a=>el.append(makeCard(a)))}
function renderAccounts(){const all=filteredAccounts();$('emptyState').hidden=state.accounts.length>0;$('content').hidden=state.accounts.length===0;renderList($('favoritesList'),all.filter(a=>a.isFavorite),'No favorites yet.');const recent=(state.recentAccountIds||[]).map(id=>state.accounts.find(a=>a.accountId===id)).filter(Boolean).filter(a=>all.includes(a)).slice(0,5);renderList($('recentList'),recent,'No recent accounts yet.');renderList($('accountsList'),all,'No matching accounts.')}
function showDialog(a){$('accountForm').reset();$('formError').hidden=true;$('editingId').value=a?.id||'';$('dialogTitle').textContent=a?'Edit Account':'Add Account';$('nameInput').value=a?.name||'';$('accountIdInput').value=a?.accountId||'';$('businessInput').value=a?.businessName||'';$('statusInput').value=a?.status||'';$('notesInput').value=a?.notes||'';$('favoriteInput').checked=!!a?.isFavorite;$('accountDialog').showModal()}

async function getActiveAdsManagerTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id || !/^https:\/\/adsmanager\.facebook\.com\//.test(tab.url||'')){throw new Error('Open Meta Ads Manager in the active tab first.')}return tab}
async function scanAdsManagerDropdown(mode='selected'){const button=mode==='auto' ? $('scanAllBtn') : $('scanSelectedBtn');const originalText=button.textContent;button.disabled=true;button.textContent='Scanning…';try{const tab=await getActiveAdsManagerTab();await chrome.scripting.executeScript({target:{tabId:tab.id},files:['scanner.js']});const result=await chrome.tabs.sendMessage(tab.id,{type:'META_ADS_SCAN_DROPDOWN',mode});if(!result?.success){throw new Error(result?.error || 'Open the Meta Ads account switcher dropdown first, then scan again.')}lastScan=result;renderScanResults(result);$('scanDialog').showModal()}catch(error){showMessage(error.message || 'Could not scan Ads Manager dropdown.')}finally{button.disabled=false;button.textContent=originalText}}
function scanCounts(result){const businesses=result.businesses||[];const flat=businesses.flatMap(b=>(b.accounts||[]).map(a=>({business:b,account:a})));const saved=new Set(state.accounts.map(a=>a.accountId));const already=flat.filter(x=>saved.has(normalizeAccountId(x.account.accountId))).length;return {businesses:businesses.length,accounts:flat.length,already,newAccounts:flat.length-already}}
function renderStat(label,value){const box=document.createElement('div');box.className='stat';const strong=document.createElement('strong');strong.textContent=String(value);const span=document.createElement('span');span.textContent=label;box.append(strong,span);return box}
function renderScanResults(result){const warnings=result.warnings||[];$('scanNotice').hidden=warnings.length===0;$('scanNotice').textContent=warnings.join('\n');const counts=scanCounts(result);$('scanStats').replaceChildren(renderStat('Businesses found',counts.businesses),renderStat('Accounts found',counts.accounts),renderStat('Already saved',counts.already),renderStat('New accounts',counts.newAccounts));const saved=new Set(state.accounts.map(a=>a.accountId));const wrap=$('scanResults');wrap.replaceChildren();(result.businesses||[]).forEach((business,businessIndex)=>{const group=document.createElement('section');group.className='business-group';const head=document.createElement('div');head.className='business-head';head.textContent=`${business.name || 'Unknown Business Portfolio'}${business.accountCountText ? ' • '+business.accountCountText : ''}${business.isSelected ? ' • selected' : ''}`;group.append(head);(business.accounts||[]).forEach((account,accountIndex)=>{const clean=normalizeAccountId(account.accountId);const isSaved=saved.has(clean);const row=document.createElement('label');row.className='account-row';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.className='scan-check';checkbox.dataset.businessIndex=String(businessIndex);checkbox.dataset.accountIndex=String(accountIndex);checkbox.disabled=isSaved;checkbox.checked=!isSaved;const info=document.createElement('div');const name=document.createElement('div');name.className='account-name';name.textContent=account.name || 'Unnamed ad account';const meta=document.createElement('div');meta.className='meta';meta.textContent=`Ad account ID: ${clean || 'Unknown'}${business.name ? ' • '+business.name : ''}`;info.append(name,meta);if(account.isSelected){const selected=document.createElement('div');selected.className='selected-note';selected.textContent='Currently selected';info.append(selected)}const badge=document.createElement('span');badge.className=isSaved?'saved-badge':'badge';badge.textContent=isSaved?'Saved':'New';row.append(checkbox,info,badge);group.append(row)});wrap.append(group)});if(!wrap.childElementCount){const p=document.createElement('p');p.className='meta';p.textContent='No ad accounts were discovered. Make sure the account switcher dropdown is open.';wrap.append(p)}}
function selectAllUnsaved(){document.querySelectorAll('.scan-check:not(:disabled)').forEach(input=>{input.checked=true})}
function unselectAllScanned(){document.querySelectorAll('.scan-check:not(:disabled)').forEach(input=>{input.checked=false})}
async function saveSelectedScannedAccounts(){if(!lastScan)return;const selected=[...document.querySelectorAll('.scan-check:checked:not(:disabled)')];if(!selected.length){$('scanSaveError').textContent='Select at least one new account to save.';$('scanSaveError').hidden=false;return}const existing=new Set(state.accounts.map(a=>a.accountId));const now=new Date().toISOString();let added=0;for(const input of selected){const business=lastScan.businesses[Number(input.dataset.businessIndex)];const account=business?.accounts?.[Number(input.dataset.accountIndex)];const clean=normalizeAccountId(account?.accountId);if(!clean || existing.has(clean))continue;state.accounts.push({id:uuid(),name:(account.name||`Ad Account ${clean}`).trim(),accountId:clean,businessName:(business.name||'').trim(),status:account.isSelected?'Selected':'',notes:'',isFavorite:false,source:'ads_manager_scan',scannedAt:now,createdAt:now,updatedAt:now});existing.add(clean);added++}await saveStorageData(state);$('scanDialog').close();renderAccounts();showMessage(`Saved ${added} account${added===1?'':'s'} from Ads Manager scan.`)}

$('accountForm').addEventListener('submit',async e=>{e.preventDefault();const editingId=$('editingId').value;const clean=normalizeAccountId($('accountIdInput').value);const data={name:$('nameInput').value.trim(),accountId:clean,businessName:$('businessInput').value.trim(),status:$('statusInput').value.trim(),notes:$('notesInput').value.trim(),isFavorite:$('favoriteInput').checked};const errors=validateAccount(data,state.accounts,editingId);if(errors.length){$('formError').textContent=errors[0];$('formError').hidden=false;return}const now=new Date().toISOString();if(editingId){const a=state.accounts.find(x=>x.id===editingId);Object.assign(a,data,{updatedAt:now})}else state.accounts.push({...data,id:uuid(),createdAt:now,updatedAt:now});await saveStorageData(state);$('accountDialog').close();renderAccounts()});
$('searchInput').addEventListener('input',e=>{query=e.target.value;renderAccounts()});$('addBtn').onclick=$('emptyAddBtn').onclick=()=>showDialog();$('manageBtn').onclick=$('optionsBtn').onclick=$('importExportBtn').onclick=()=>chrome.runtime.openOptionsPage();$('cancelDialog').onclick=()=>$('accountDialog').close();$('scanSelectedBtn').onclick=()=>scanAdsManagerDropdown('selected');$('scanAllBtn').onclick=()=>scanAdsManagerDropdown('auto');$('rescanBtn').onclick=()=>scanAdsManagerDropdown('selected');$('selectAllNewBtn').onclick=selectAllUnsaved;$('unselectAllBtn').onclick=unselectAllScanned;$('saveScannedBtn').onclick=saveSelectedScannedAccounts;$('cancelScanBtn').onclick=$('closeScanBtn').onclick=()=>$('scanDialog').close();
$('openInBackgroundInput').addEventListener('change',async e=>{state.settings={...STORAGE_DEFAULT.settings,...(state.settings||{}),openInBackground:e.target.checked};await saveStorageData(state)});
getStorageData().then(d=>{state=d;$('openInBackgroundInput').checked=state.settings.openInBackground;renderAccounts()});
