const STORAGE_DEFAULT = { accounts: [], recentAccountIds: [] };
const ADS_URL = 'https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=';
const $ = (id) => document.getElementById(id);
let state = structuredClone(STORAGE_DEFAULT);
let query = '';
async function getStorageData(){try{return {...STORAGE_DEFAULT,...await chrome.storage.sync.get(STORAGE_DEFAULT)}}catch(e){showMessage('Could not read storage.');return structuredClone(STORAGE_DEFAULT)}}
async function saveStorageData(data){try{await chrome.storage.sync.set(data);return true}catch(e){showMessage('Could not save changes.');return false}}
function normalizeAccountId(v){return String(v||'').trim().replace(/^act_/i,'').replace(/\D/g,'')}
function validateAccount(a, existing, editingId){const errors=[]; if(!a.name.trim())errors.push('Account name cannot be empty.'); if(!normalizeAccountId(a.accountId))errors.push('Account ID cannot be empty.'); const clean=normalizeAccountId(a.accountId); if(clean&&existing.some(x=>x.accountId===clean&&x.id!==editingId))errors.push('This account ID already exists.'); return errors}
function showMessage(t){const el=$('message');el.textContent=t;el.hidden=false;setTimeout(()=>el.hidden=true,3500)}
function uuid(){return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`}
async function openAdsAccount(accountId){await chrome.tabs.create({url:ADS_URL+accountId}); await updateRecentAccounts(accountId)}
async function updateRecentAccounts(accountId){state.recentAccountIds=[accountId,...state.recentAccountIds.filter(id=>id!==accountId)].slice(0,5);await saveStorageData(state);renderAccounts()}
async function toggleFavorite(id){const a=state.accounts.find(x=>x.id===id); if(!a)return; a.isFavorite=!a.isFavorite; a.updatedAt=new Date().toISOString(); await saveStorageData(state); renderAccounts()}
async function deleteAccount(id){const a=state.accounts.find(x=>x.id===id); if(!a||!confirm(`Delete ${a.name}?`))return; state.accounts=state.accounts.filter(x=>x.id!==id); state.recentAccountIds=state.recentAccountIds.filter(x=>x!==a.accountId); await saveStorageData(state); renderAccounts()}
function filteredAccounts(){const q=query.toLowerCase(); return state.accounts.filter(a=>[a.name,a.accountId,a.businessName,a.status].some(v=>String(v||'').toLowerCase().includes(q))).sort((a,b)=>(b.isFavorite-a.isFavorite)||a.name.localeCompare(b.name))}
function makeCard(a){const card=document.createElement('article');card.className='card';card.tabIndex=0;card.addEventListener('click',()=>openAdsAccount(a.accountId));card.addEventListener('keydown',e=>{if(e.key==='Enter')openAdsAccount(a.accountId)});const top=document.createElement('div');top.className='card-top';const info=document.createElement('div');const name=document.createElement('div');name.className='name';name.textContent=a.name;const meta=document.createElement('div');meta.className='meta';meta.textContent=`${a.accountId}${a.businessName?' • '+a.businessName:''}`;info.append(name,meta);if(a.status){const badge=document.createElement('span');badge.className='badge';badge.textContent=a.status;info.append(badge)}const star=document.createElement('button');star.className='tiny';star.textContent=a.isFavorite?'★':'☆';star.title='Toggle favorite';star.addEventListener('click',e=>{e.stopPropagation();toggleFavorite(a.id)});top.append(info,star);const actions=document.createElement('div');actions.className='card-actions';[['Open','open',()=>openAdsAccount(a.accountId)],['Edit','secondary',()=>showDialog(a)],['Delete','danger',()=>deleteAccount(a.id)]].forEach(([t,c,fn])=>{const b=document.createElement('button');b.className=`tiny ${c}`;b.textContent=t;b.addEventListener('click',e=>{e.stopPropagation();fn()});actions.append(b)});card.append(top,actions);return card}
function renderList(el, accounts, emptyText){el.replaceChildren(); if(!accounts.length){const p=document.createElement('p');p.className='meta';p.textContent=emptyText;el.append(p);return} accounts.forEach(a=>el.append(makeCard(a)))}
function renderAccounts(){const all=filteredAccounts();$('emptyState').hidden=state.accounts.length>0;$('content').hidden=state.accounts.length===0;renderList($('favoritesList'),all.filter(a=>a.isFavorite),'No favorites yet.');const recent=state.recentAccountIds.map(id=>state.accounts.find(a=>a.accountId===id)).filter(Boolean).filter(a=>all.includes(a));renderList($('recentList'),recent,'No recent accounts yet.');renderList($('accountsList'),all,'No matching accounts.')}
function showDialog(a){$('accountForm').reset();$('formError').hidden=true;$('editingId').value=a?.id||'';$('dialogTitle').textContent=a?'Edit Account':'Add Account';$('nameInput').value=a?.name||'';$('accountIdInput').value=a?.accountId||'';$('businessInput').value=a?.businessName||'';$('statusInput').value=a?.status||'';$('notesInput').value=a?.notes||'';$('favoriteInput').checked=!!a?.isFavorite;$('accountDialog').showModal()}
$('accountForm').addEventListener('submit',async e=>{e.preventDefault();const editingId=$('editingId').value;const clean=normalizeAccountId($('accountIdInput').value);const data={name:$('nameInput').value.trim(),accountId:clean,businessName:$('businessInput').value.trim(),status:$('statusInput').value.trim(),notes:$('notesInput').value.trim(),isFavorite:$('favoriteInput').checked};const errors=validateAccount(data,state.accounts,editingId);if(errors.length){$('formError').textContent=errors[0];$('formError').hidden=false;return}const now=new Date().toISOString();if(editingId){const a=state.accounts.find(x=>x.id===editingId);Object.assign(a,data,{updatedAt:now})}else state.accounts.push({...data,id:uuid(),createdAt:now,updatedAt:now});await saveStorageData(state);$('accountDialog').close();renderAccounts()});
$('searchInput').addEventListener('input',e=>{query=e.target.value;renderAccounts()});$('addBtn').onclick=$('emptyAddBtn').onclick=()=>showDialog();$('manageBtn').onclick=$('optionsBtn').onclick=$('importExportBtn').onclick=()=>chrome.runtime.openOptionsPage();$('cancelDialog').onclick=()=>$('accountDialog').close();
getStorageData().then(d=>{state=d;renderAccounts()});
